# Generated by Django 5.0.6 on 2024-05-21 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('restaurant_name', models.CharField(max_length=255)),
                ('establishment_year', models.IntegerField(blank=True, null=True)),
                ('banner_img', models.FileField(upload_to='media/')),
                ('number_chefs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menucuisine')),
            ],
        ),
    ]
