# Generated by Django 5.0.6 on 2024-05-22 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date_time',
        ),
    ]
